<Login>:
    
    MDFloatLayout:
        md_bg_color: 1, 1, 1, 1
    MDIconButton:
        icon: "arrow-left"
        pos_hint: {"center_x": 0.2, "center_y": 0.8}
        on_release:
            root.manager.transition.direction = "right"
            root.manager.current = 'welcome'
    MDLabel:
        text:"Login Screen"
        halign: "center"
        font_size: "25sp"
        font_name: "tech"
        pos_hint: {'center_y': 0.5}
    
    
   